-- 查询注册送多少红包：【加缓存、管理台配置清除缓存】
BsRedPacketCheckMapper.autoRedPacketTotalGrid - ==>  Preparing: SELECT a.subtract, b.agent_ids FROM `bs_red_packet_check` a, bs_auto_red_packet_rule b WHERE a.serial_no = b.serial_no AND b.`status` = 'AVAILABLE' AND a.check_status = 'PASS' AND a.distribute_type = 'AUTO' AND (b.agent_ids LIKE '%0%' OR b.agent_ids LIKE '%-1%') AND b.trigger_type = ? AND b.distribute_time_start < NOW() AND b.distribute_time_end > NOW() 
BsRedPacketCheckMapper.autoRedPacketTotalGrid - ==> Parameters: NEW_USER(String)
BsRedPacketCheckMapper.autoRedPacketTotalGrid - <==      Total: 0

-- 产品列表【加缓存，默认全部，重载方法，sql需要优化，购买成功时清除】
BsProductMapper.selectProductGrid - ==>  Preparing: SELECT * FROM (( SELECT * FROM ( SELECT ( SELECT COUNT(sub.id) FROM bs_sub_account sub WHERE sub.product_type in ('REG', 'AUTH', 'AUTH_YUN', 'AUTH_ZSD') AND sub.`status` IN (2,5,7) AND sub.product_id = a.id ) AS invest_count, a.*, c.property_symbol FROM bs_product a, bs_user_type_auth b, bs_property_info c WHERE FIND_IN_SET(?, a.show_terminal) AND b.user_type = ? AND a.id = b.product_id AND a.`status` IN (6, 5) AND a.property_id = c.id ORDER BY a.is_suggest DESC, a.`status` DESC, a.update_time DESC, a.id DESC ) AS aa ) UNION ( SELECT * FROM ( SELECT ( SELECT COUNT(sub.id) FROM bs_sub_account sub WHERE sub.product_type in ('REG', 'AUTH', 'AUTH_YUN', 'AUTH_ZSD') AND sub.`status` IN (2,5,7) AND sub.product_id = a2.id ) AS invest_count, a2.*, c2.property_symbol FROM bs_product a2, bs_user_type_auth b2, bs_property_info c2 WHERE FIND_IN_SET(?, a2.show_terminal) AND b2.user_type = ? AND a2.id = b2.product_id AND a2.`status` = 7 AND a2.property_id = c2.id ORDER BY a2.update_time DESC, a2.id DESC ) AS cc ) ) AS aaa LIMIT ?, ? 
BsProductMapper.selectProductGrid - ==> Parameters: PC(String), NORMAL(String), PC(String), NORMAL(String), 0(Integer), 12(Integer)
BsProductMapper.selectProductGrid - <==      Total: 12
-- 产品列表个数【加缓存，默认全部，重载方法，sql需要优化，购买成功时清除】
BsProductMapper.countProductGrid - ==>  Preparing: SELECT COUNT(a.id) FROM bs_product a, bs_user_type_auth b WHERE FIND_IN_SET(?, a.show_terminal) AND b.user_type = ? AND a.id = b.product_id AND a.`status` IN (6, 5, 7) 
BsProductMapper.countProductGrid - ==> Parameters: PC(String), NORMAL(String)
BsProductMapper.countProductGrid - <==      Total: 1

--【可删除，将sql合并到产品列表sql中】循环上述列表，并查询产品状态以及是否推荐
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3441(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3461(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3460(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3458(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3457(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3451(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3448(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3447(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3446(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3445(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3443(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1
BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
BsProductMapper.selectByPrimaryKey - ==> Parameters: 3442(Integer)
BsProductMapper.selectByPrimaryKey - <==      Total: 1

-- 产品列表banner【放缓存、发布时清除】
BsBannerConfigMapper.selectByExample - ==>  Preparing: select id, channel, subject, url, img_path, priority, status, m_user_id, create_time, update_time, show_page, activity_type from bs_banner_config WHERE ( show_page = ? and channel = ? and status = ? ) 
BsBannerConfigMapper.selectByExample - ==> Parameters: DEPSUBJECT(String), GEN(String), SHOW(String)
BsBannerConfigMapper.selectByExample - <==      Total: 1