-- 定期产品列表
2018-05-02 10:24:15,463 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectProductGrid - ==>  Preparing: SELECT * FROM (( SELECT * FROM ( SELECT ( SELECT COUNT(sub.id) FROM bs_sub_account sub WHERE sub.product_type in ('REG', 'AUTH', 'AUTH_YUN', 'AUTH_ZSD') AND sub.`status` IN (2,5,7) AND sub.product_id = a.id ) AS invest_count, a.*, c.property_symbol FROM bs_product a, bs_user_type_auth b, bs_property_info c WHERE FIND_IN_SET(?, a.show_terminal) AND b.user_type = ? AND a.id = b.product_id AND a.`status` IN (6, 5) AND a.property_id = c.id ORDER BY a.is_suggest DESC, a.`status` DESC, a.update_time DESC, a.id DESC ) AS aa ) UNION ( SELECT * FROM ( SELECT ( SELECT COUNT(sub.id) FROM bs_sub_account sub WHERE sub.product_type in ('REG', 'AUTH', 'AUTH_YUN', 'AUTH_ZSD') AND sub.`status` IN (2,5,7) AND sub.product_id = a2.id ) AS invest_count, a2.*, c2.property_symbol FROM bs_product a2, bs_user_type_auth b2, bs_property_info c2 WHERE FIND_IN_SET(?, a2.show_terminal) AND b2.user_type = ? AND a2.id = b2.product_id AND a2.`status` = 7 AND a2.property_id = c2.id ORDER BY a2.update_time DESC, a2.id DESC ) AS cc ) ) AS aaa WHERE aaa.return_type = ? LIMIT ?, ? 
2018-05-02 10:24:15,464 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectProductGrid - ==> Parameters: H5(String), NORMAL(String), H5(String), NORMAL(String), FINISH_RETURN_ALL(String), 0(Integer), 10(Integer)
2018-05-02 10:24:16,632 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectProductGrid - <==      Total: 10

-- 定期产品列表个数
2018-05-02 10:24:16,634 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.countProductGrid - ==>  Preparing: SELECT COUNT(a.id) FROM bs_product a, bs_user_type_auth b WHERE FIND_IN_SET(?, a.show_terminal) AND b.user_type = ? AND a.id = b.product_id AND a.`status` IN (6, 5, 7) AND a.return_type = ? 
2018-05-02 10:24:16,635 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.countProductGrid - ==> Parameters: H5(String), NORMAL(String), FINISH_RETURN_ALL(String)
2018-05-02 10:24:16,700 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.countProductGrid - <==      Total: 1

--【可删除，将sql合并到产品列表sql中】循环上述列表，并查询产品状态以及是否推荐
2018-05-02 10:24:16,702 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:16,702 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3441(Integer)
2018-05-02 10:24:16,716 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:16,719 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:16,719 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3458(Integer)
2018-05-02 10:24:16,768 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:16,769 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:16,769 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3451(Integer)
2018-05-02 10:24:16,796 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:16,798 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:16,798 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3448(Integer)
2018-05-02 10:24:16,854 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:16,856 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:16,856 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3447(Integer)
2018-05-02 10:24:16,914 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:16,917 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:16,918 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3446(Integer)
2018-05-02 10:24:16,980 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:16,982 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:16,982 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3445(Integer)
2018-05-02 10:24:17,001 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:17,003 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:17,003 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3443(Integer)
2018-05-02 10:24:17,018 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:17,018 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:17,019 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3442(Integer)
2018-05-02 10:24:17,033 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:17,034 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:17,034 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3440(Integer)
2018-05-02 10:24:17,048 [qtp1486365718-34] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1

-- 分期产品列表
2018-05-02 10:24:17,057 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectProductGrid - ==>  Preparing: SELECT * FROM (( SELECT * FROM ( SELECT ( SELECT COUNT(sub.id) FROM bs_sub_account sub WHERE sub.product_type in ('REG', 'AUTH', 'AUTH_YUN', 'AUTH_ZSD') AND sub.`status` IN (2,5,7) AND sub.product_id = a.id ) AS invest_count, a.*, c.property_symbol FROM bs_product a, bs_user_type_auth b, bs_property_info c WHERE FIND_IN_SET(?, a.show_terminal) AND b.user_type = ? AND a.id = b.product_id AND a.`status` IN (6, 5) AND a.property_id = c.id ORDER BY a.is_suggest DESC, a.`status` DESC, a.update_time DESC, a.id DESC ) AS aa ) UNION ( SELECT * FROM ( SELECT ( SELECT COUNT(sub.id) FROM bs_sub_account sub WHERE sub.product_type in ('REG', 'AUTH', 'AUTH_YUN', 'AUTH_ZSD') AND sub.`status` IN (2,5,7) AND sub.product_id = a2.id ) AS invest_count, a2.*, c2.property_symbol FROM bs_product a2, bs_user_type_auth b2, bs_property_info c2 WHERE FIND_IN_SET(?, a2.show_terminal) AND b2.user_type = ? AND a2.id = b2.product_id AND a2.`status` = 7 AND a2.property_id = c2.id ORDER BY a2.update_time DESC, a2.id DESC ) AS cc ) ) AS aaa WHERE aaa.return_type = ? LIMIT ?, ? 
2018-05-02 10:24:17,058 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectProductGrid - ==> Parameters: H5(String), NORMAL(String), H5(String), NORMAL(String), AVERAGE_CAPITAL_PLUS_INTEREST(String), 0(Integer), 10(Integer)
2018-05-02 10:24:17,845 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectProductGrid - <==      Total: 10

-- 分期产品个数
2018-05-02 10:24:17,847 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.countProductGrid - ==>  Preparing: SELECT COUNT(a.id) FROM bs_product a, bs_user_type_auth b WHERE FIND_IN_SET(?, a.show_terminal) AND b.user_type = ? AND a.id = b.product_id AND a.`status` IN (6, 5, 7) AND a.return_type = ? 
2018-05-02 10:24:17,847 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.countProductGrid - ==> Parameters: H5(String), NORMAL(String), AVERAGE_CAPITAL_PLUS_INTEREST(String)
2018-05-02 10:24:17,886 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.countProductGrid - <==      Total: 1

--【可删除，将sql合并到产品列表sql中】循环上述列表，并查询产品状态以及是否推荐
2018-05-02 10:24:17,887 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:17,888 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3428(Integer)
2018-05-02 10:24:17,902 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:17,904 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:17,904 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3426(Integer)
2018-05-02 10:24:17,918 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:17,919 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:17,919 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3427(Integer)
2018-05-02 10:24:17,933 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:17,934 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:17,934 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3433(Integer)
2018-05-02 10:24:17,949 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:17,950 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:17,951 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3407(Integer)
2018-05-02 10:24:17,971 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:17,972 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:17,973 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3411(Integer)
2018-05-02 10:24:17,988 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:17,990 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:17,990 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3292(Integer)
2018-05-02 10:24:18,002 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:18,003 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:18,004 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3226(Integer)
2018-05-02 10:24:18,020 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:18,021 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:18,021 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3264(Integer)
2018-05-02 10:24:18,047 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1
2018-05-02 10:24:18,049 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==>  Preparing: select id, name, type, activity_type, code, interest_type, base_rate, max_rate, term, max_total_amount, min_invest_amount, max_single_invest_amount, max_invest_amount, max_invest_times, start_time, end_time, curr_total_amount, status, note, invest_num, sys_return_rate, serial_id, serial_order, serial_name, property_type, begin_interest_days, return_type, interest_deal, is_support_transfer, manage_fee, show_terminal, property_id, is_suggest, terminator, finish_time, checker, check_time, distributor, distribute_time, is_support_red_packet, create_time, update_time, is_support_incr_interest from bs_product where id = ? 
2018-05-02 10:24:18,050 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - ==> Parameters: 3262(Integer)
2018-05-02 10:24:18,071 [qtp1486365718-33] DEBUG com.pinting.business.dao.BsProductMapper.selectByPrimaryKey - <==      Total: 1

-- banner
2018-05-02 10:24:18,191 [qtp1486365718-31] DEBUG com.pinting.business.dao.BsBannerConfigMapper.selectByExample - ==>  Preparing: select id, channel, subject, url, img_path, priority, status, m_user_id, create_time, update_time, show_page, activity_type from bs_banner_config WHERE ( show_page = ? and channel = ? and status = ? ) 
2018-05-02 10:24:18,192 [qtp1486365718-31] DEBUG com.pinting.business.dao.BsBannerConfigMapper.selectByExample - ==> Parameters: DEPSUBJECT(String), MICRO(String), SHOW(String)
2018-05-02 10:24:18,204 [qtp1486365718-31] DEBUG com.pinting.business.dao.BsBannerConfigMapper.selectByExample - <==      Total: 0

-- banner
2018-05-02 10:24:18,208 [qtp1486365718-31] DEBUG com.pinting.business.dao.BsBannerConfigMapper.selectByExample - ==>  Preparing: select id, channel, subject, url, img_path, priority, status, m_user_id, create_time, update_time, show_page, activity_type from bs_banner_config WHERE ( status = ? and channel = ? and show_page in ( ? , ? , ? ) ) 
2018-05-02 10:24:18,209 [qtp1486365718-31] DEBUG com.pinting.business.dao.BsBannerConfigMapper.selectByExample - ==> Parameters: SHOW(String), MICRO(String), DEPSUBJECT(String), ZANSTAGES(String), ESTUARYPLAN(String)
2018-05-02 10:24:18,220 [qtp1486365718-31] DEBUG com.pinting.business.dao.BsBannerConfigMapper.selectByExample - <==      Total: 0
